import type { Metadata } from "next";
import "./globals.css";
import { Geist } from "next/font/google";
import { cn } from "@/lib/utils";
import { LanguageProvider } from "@/lib/language-context";
import Header from "@/page-components/header";
import Footer from "@/page-components/footer";

const geist = Geist({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Web Services Bulgaria",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="bg" className={cn("h-full", "font-sans", geist.variable)}>
      <body
        suppressHydrationWarning
        className="min-h-screen max-w-480 m-auto! flex flex-col overflow-x-hidden"
      >
        <LanguageProvider>
          <Header />
          {children}
          <Footer />
        </LanguageProvider>
      </body>
    </html>
  );
}
